receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  attributes:
    actions:
      - key: loki.format
        value: json
        action: insert

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
  
  debug:
    verbosity: detailed
  
  otlp:
    endpoint: otel-collector:4317
    tls:
      insecure: true
  
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true
  
  sentry:
    dsn: http://5a9b85bb26024e7ea7f60e10f5d0d29f@sentry:9000/1
    environment: production

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp, sentry]
    
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]
    
    logs:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [debug, loki]
